### ISSUE TITLE
integrer la page des statistiques admin + staff

### ISSUE THREAD

**Issue by omarKazoum** [omarKazoum/YoucodeRestaurant#38]

**Comment by omarKazoum** [comment]
c'est pour toi TAHA
voici les images a coder 
https://drive.google.com/file/d/1-DghxgTJoIXkR2aeY4OXnQs7zykH0UjY/view?usp=sharing, https://drive.google.com/file/d/196CQQunoY5SYic_UVs94L5ZrkC2Bht53/view?usp=sharing

**Comment by dev-taha-2000** [comment]
d'acord

**Comment by dev-taha-2000** [comment]
ok
